### ISSUE TITLE
你好作者，我看着SecuritySettings这个自定义配置类和Yml文件中的有些字段值不一样，到底以哪个为主。

### ISSUE THREAD

**Issue by luzhu123** [chenfromsz/spring-boot-security#1]
你好作者，我看着SecuritySettings这个自定义配置类和Yml文件中的有些字段值不一样，到底以哪个为主。

public class SecuritySettings {
    private String logoutsuccssurl = "/logout";
    private String permitall = "/api";
    private String deniedpage = "/deny";
    private String urlroles;

而在yml文件中，则是：
securityconfig:
  logoutsuccssurl: /
  permitall: /rest/**,/bbs**
  deniedpage: /deny
  urlroles: /**/new/** = admin;
            /**/edit/** = admin,editor;
            /**/delete/** = admin
这样的话是不是在上面那个类中就不需要赋初值了。

**Comment by chenfromsz** [comment]
是的，初值会被覆盖。如果读取不到配置时才使用初值。
